apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c3d3f470b-java-springboot
  janus-idp.io/tekton: c3d3f470b-java-springboot
  backstage.io/kubernetes-id: c3d3f470b-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c3d3f470b-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
